name: Validação automática

on:
  schedule:
    # Every day at 15:40 UTC
    - cron: '40 15 * * *'

jobs:
  run-validation-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Run validation scripts
        run: |
          sudo apt install curl git html-xml-utils wget -y
          "${GITHUB_WORKSPACE}/scripts/01-parlamento.sh"
          "${GITHUB_WORKSPACE}/scripts/02-economia.sh"
          "${GITHUB_WORKSPACE}/scripts/07-lisboa-pdf.sh"
          "${GITHUB_WORKSPACE}/scripts/09-financas.sh"
          "${GITHUB_WORKSPACE}/scripts/12-autentic.sh"
          "${GITHUB_WORKSPACE}/scripts/14-mai.sh"
          "${GITHUB_WORKSPACE}/scripts/15-rcaap.sh"
          "${GITHUB_WORKSPACE}/scripts/16-saude.sh"
          "${GITHUB_WORKSPACE}/scripts/20-viva.sh"
          "${GITHUB_WORKSPACE}/scripts/25-eleicoes.sh"
          "${GITHUB_WORKSPACE}/scripts/26-snirh.sh"
          "${GITHUB_WORKSPACE}/scripts/29-inpi.sh"
          "${GITHUB_WORKSPACE}/scripts/35-turismo.sh"
          "${GITHUB_WORKSPACE}/scripts/36-norte2020.sh"
          "${GITHUB_WORKSPACE}/scripts/40-sef.sh"
          "${GITHUB_WORKSPACE}/scripts/50-bud.sh"
          "${GITHUB_WORKSPACE}/scripts/51-dgeg.sh"
          "${GITHUB_WORKSPACE}/scripts/53-sg-pcm-gov.sh"
          "${GITHUB_WORKSPACE}/scripts/55-anqep.sh"
          "${GITHUB_WORKSPACE}/scripts/56-territorio.sh"

      - name: Commit file(s)
        run: |
          git config --local user.email "<>"
          git config --local user.name "GitHub Actions"
          git add ./README.md
          git commit -m "Update de $(date +"%Y-%m-%d")"

      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
